Grid lookup wildcard
minova-afis/aero.minova.rcp pull request #1145
Opened 2022-02-04 14:44 UTC by Bauer-David

2022-02-07 07:24 UTC, janiak-minova requested changes
Aktuell ist das Verhalten nicht so wie erwartet. An den Regex muss IMMER ein * angehängt werden, damit alle Ergebnisse aufgelistet werden, die mit dem eingegebenen Pattern beginnen (siehe Verhalten in "normalen" Lookups).

2022-02-07 07:24 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WildcardMatcher.java
> +public class WildcardMatcher {
Diese Util Klasse sollte auch überall genutzt werden. Entsprechend bitte auch den Code zum Bauen des Regex im  `LookupContentProvider` mit den Methoden dieser Klasse ersetzen.

Außerdem sollte diese Klasse `Matcher` erweitern, dann muss die `matches` Methode nicht selbst implementiert werden.

2022-02-07 07:24 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/nattable/MinovaNatCombo.java
> +					if (!text.getText().isBlank() && (text.getText().contains("%") || text.getText().contains("_"))) {
`!text.getText().isBlank()` kann entfernt werden, wenn % oder _ enthalten sind ist der text eh nicht leer.

Ich würde diesen if-Block komplett entfernen und immer den Matcher nutzen.

2022-02-07 11:52 UTC, Bauer-David commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/nattable/MinovaNatCombo.java
> +					if (!text.getText().isBlank() && (text.getText().contains("%") || text.getText().contains("_"))) {
Ohne den If-Block ist die Auswahl tatsächlich leer. Sonst muss das Wort ausgeschrieben werde, dass ein Ergebnis angezeigt wird.

2022-02-07 11:53 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/nattable/MinovaNatCombo.java
> +					if (!text.getText().isBlank() && (text.getText().contains("%") || text.getText().contains("_"))) {
Deswegen habe ich ganz oben ja gemeint, dass am Ende immer ein * angehängt werden muss.

2022-02-07 12:10 UTC, Bauer-David commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/nattable/MinovaNatCombo.java
> +					if (!text.getText().isBlank() && (text.getText().contains("%") || text.getText().contains("_"))) {
Ahhh

2022-02-07 12:12 UTC, Bauer-David commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WildcardMatcher.java
> +public class WildcardMatcher {
Mit welchem Matches soll ich den erweitern, da ich nur mancher nicht angezeigt kriege

2022-02-07 12:13 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WildcardMatcher.java
> +public class WildcardMatcher {
java.util.regex.Matcher

2022-02-07 12:13 UTC, Bauer-David commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WildcardMatcher.java
> +public class WildcardMatcher {
ok, thx

2022-02-07 15:31 UTC, janiak-minova commented on bundles/aero.minova.rcp.widgets/src/aero/minova/rcp/widgets/LookupContentProvider.java
> +		WildcardMatcher matcher = new WildcardMatcher(entry.toUpperCase() + "%");
Bitte die nicht mehr genutzte Methode auch entfernen

2022-02-08 07:41 UTC, janiak-minova approved these changes

2022-02-09 12:44 UTC, merged