Schriftgröße im PreferenceWindow anpassen
minova-afis/aero.minova.rcp pull request #1154
Opened 2022-02-11 08:36 UTC by Bauer-David

2022-02-11 15:00 UTC, janiak-minova commented
Bitte auch Pullrequests in workingtime (WorkingTimePreferencePage) und invoice (InvoicePreferencePage) aufmachen, in denen der neue Konstruktor-Aufruf genutzt wird.
Ich denke, dadurch das jetzt die Image-Util genutzt wird müssen die Icons für die Stundenerfassung- und Vorgangseinstellungen auch nicht mehr im Hauptprojekt liegen, sondern können mit den anderen Images vom CAS geladen werden.

Außerdem passt die Schriftgröße unter den Bildern nicht zu der eingestellten Größe. Kann das noch im css ergänzt werden?
<img width="561" alt="Bildschirmfoto 2022-02-11 um 15 58 55" src="https://user-images.githubusercontent.com/77741125/153614815-96f8031c-bced-46e4-9ca0-a8c8a46db021.png">

2022-02-11 15:01 UTC, janiak-minova requested changes
Bitte auch Pullrequests in workingtime (WorkingTimePreferencePage) und invoice (InvoicePreferencePage) aufmachen, in denen der neue Konstruktor-Aufruf genutzt wird.
Ich denke, dadurch das jetzt die Image-Util genutzt wird müssen die Icons für die Stundenerfassung- und Vorgangseinstellungen auch nicht mehr im Hauptprojekt liegen, sondern können mit den anderen Images vom CAS geladen werden.
Entsprechen Image-Ordner Invoice und SIS löschen (und ggf. in den src/main/app/images Ordner der Masken eintragen).
Eigentlich sollte aber das Icon für die Einstellungen der Stundenerfassungen auch das Uhr-Icon der eigentlichen Maske sein, also benötigen wir die SIS-Icons gar nicht.

Außerdem passt die Schriftgröße unter den Bildern nicht zu der eingestellten Größe. Kann das noch im css ergänzt werden?
<img width="561" alt="Bildschirmfoto 2022-02-11 um 15 58 55" src="https://user-images.githubusercontent.com/77741125/153614815-96f8031c-bced-46e4-9ca0-a8c8a46db021.png">

2022-02-15 08:20 UTC, Bauer-David commented
Ich habe die Änderungen unter Windows getestet und angeschaut. Die Comboboxen benötigen nur unter Mac die manuelle Höhen Anpassung. Unter Windows sind sowohl die Combos, als auch die Buttons automatisch richtig angepasst.

2022-02-16 10:14 UTC, Bauer-David commented
Wir warten noch auf das kleinere InfoIcon für die Tooltips in den Preferences. Sobald das drin ist kann der PullRequest abgeschlossen werden.

2022-02-16 13:26 UTC, janiak-minova commented
Bitte noch folgende Änderungen:

- [ ] Ordner images/Invoice und images/SIS im images-Plugin löschen. Die Icons werden nicht für die Anwendung allgemein benötigt, sondern nur, wenn die entsprechenden Masken eingebunden sind. Entsprechend sollen die Icons auch mit den Projekten ausgeliefert werden. Für Invoice ist das eh schon der Fall, SIS siehe Kommentar zum Pullrequest im workingtime-Repository [#15](https://github.com/minova-afis/aero.minova.workingtime/pull/15)
- [ ] icons Ornder im preferencewindow-Plugin komplett löschen (inkl. Circled-I.png, das wird ja anscheinend nicht mehr benötigt)

2022-02-21 13:15 UTC, janiak-minova approved these changes

2022-02-21 13:16 UTC, merged