#1098 tab reihenfolge
minova-afis/aero.minova.rcp pull request #1158
Opened 2022-02-16 15:08 UTC by Bauer-David

2022-02-17 08:00 UTC, Bauer-David commented
Unter Windows (Parallels) getestet und es verhält sich exakt wie auf MacOs

2022-02-17 08:15 UTC, janiak-minova requested changes

2022-02-17 08:15 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/parts/WFCDetailPart.java
> +		section.addControlListener(new ControlListener() {
Hier stattdessen einen `ControlAdapter` nutzen, dann kann die Methode `controlResized(ControlEvent e)`, die nicht gebraucht wird, entfernt werden.

2022-02-17 08:15 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/TabUtil.java
> +			int order1 = ((MinovaSectionData) f1.getLayoutData()).order;
Vorher überprüfen, ob eine von den Sections unten angeordnet werden soll (`horizontalFill=true`).

Die `order` nur nutzen, wenn beide Sections den gleichen Wert für `horizontalFill` haben.

2022-02-17 08:15 UTC, janiak-minova commented on bundles/aero.minova.rcp.css/src/aero/minova/rcp/css/widgets/DetailLayout.java
> +		int order = -1;
Mit den Anpassungen der Methode `getSortedSectionTabList()` können die Änderungen an dieser Klasse komplett rückgängig gemacht werden.

2022-02-21 08:48 UTC, janiak-minova approved these changes

2022-02-21 08:49 UTC, merged