Tab-Reihenfolge während der Laufzeit aktualisieren
minova-afis/aero.minova.rcp pull request #1161
Opened 2022-02-23 07:22 UTC by Bauer-David

2022-02-25 14:26 UTC, janiak-minova requested changes
Funktioniert prinzipiell, bitte Code nur etwas aufräumen.

2022-02-25 14:26 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/handlers/SetNewTabHandler.java
> +			detail.getParent().getParent().getParent().setTabList(TabUtil.getTabListForPart(detail.getParent().getParent().getParent(), selectAllControls));
Diese Aufrufe mit `.getComposite().getChildren()[0]).getChildren()[0]` und `detail.getParent().getParent().getParent()` sind schon sehr unübersichtlich und fehleranfällig. Kannst du die entsprechenden Composites entweder im WFCDetailPart speichern und über eine Methode aufrufen oder über ein `set-/getData()` mit einer entsprechenden Konstante erreichbar machen?

2022-02-25 14:26 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/parts/WFCDetailPart.java
> +		section.setData(Constants.MSECTION, mSection);
Ist genau dafür nicht der SectionAccessor? Um aus der MinovaSection die MSection und umgekehrt zu bekommen?

2022-02-25 14:27 UTC, janiak-minova commented
Außerdem steht in dem Issue etwas von Datums- und Zeitpattern die ohne Neustart gesetzt werden sollen.

2022-03-07 08:53 UTC, Bauer-David commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/parts/WFCDetailPart.java
> +		section.setData(Constants.MSECTION, mSection);
Ja, nur kommt man nicht über die Section an den SectionAccessor um die Section zu holen

2022-03-07 09:56 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/parts/WFCDetailPart.java
> +		section.setData(Constants.MSECTION, mSection);
Die Section ist inzwischen ja die MinovaSection, also eine Klasse von uns. Der könnten wir den SecitonAccessor (oder auch gleich die MSection) geben. Oder gibt das zirkuläre Abhängigkeiten?

2022-11-10 15:25 UTC, closed without merging