NumberField TextAssist
minova-afis/aero.minova.rcp pull request #1396
Opened 2022-11-18 14:02 UTC by Bauer-David

closes #1394 
closes #1404

2023-01-19 07:14 UTC, janiak-minova requested changes
<img width="482" alt="Bildschirmfoto 2023-01-19 um 08 10 06" src="https://user-images.githubusercontent.com/77741125/213378052-017efb56-e59d-4d09-846b-06cccfa0f111.png">

In den Feldern ist keine Message mehr, ist das gewollt?


<img width="505" alt="Bildschirmfoto 2023-01-19 um 08 12 10" src="https://user-images.githubusercontent.com/77741125/213378496-10bf806e-1244-413d-8bcf-cfcda8af9abc.png">


Außerdem sind die Texte links ausgerichtet. Bei Zahlen war es bisher rechts.

2023-01-19 07:14 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/accessor/NumberValueAccessor.java
> +//	@Override
Auskommentierten Code entfernen

2023-01-19 07:14 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/fields/NumberField.java
> +				numberFormat.setGroupingUsed(true);
Das würde ich nicht jedes mal in der getContent Methode neu erstellen, sondern einmal in der überliegenden Methode

2023-01-20 08:07 UTC, Bauer-David commented
Der Text ist jetzt rechts aligned und die Nebula Widgets sind auf die neuste Version aktualisiert. Ich habe gleich als Download URL /latest gesetzt, so wird bei Update die neuste Version gezogen.

2023-01-23 14:56 UTC, janiak-minova commented
Das Alignment passt jetzt, die "message" (also der graue Text mit z.B. `000.000.000`) fehlt immer noch. Ist das gewollt?

2023-01-24 07:07 UTC, janiak-minova approved these changes
Der Changelog-Eintrag ist in einen früheren Release reingerutscht, das bitte noch ändern. Ansonsten passt alles.

Auf Windows habe ich es auch kurz probiert, sieht gut aus.

2023-01-24 10:19 UTC, merged