Bad keybinding Korrektur/Erweiterung
minova-afis/aero.minova.rcp pull request #1416
Opened 2023-01-31 08:54 UTC by Bauer-David

closes #1414 
closes #1413

2023-01-31 13:48 UTC, janiak-minova requested changes
Funktioniert prinzipel, allerdings werden folgende Annahmen gemacht:
- Die Indexview hat die Spalten `KeyLong` und `KeyText`
- Es gibt genau eine ID-Spalte, die `KeyLong` heißen muss

Für den Großteil unserer Masken sollte das kein Problem sein, es muss uns aber bewusst sein.

Es wäre möglich, die Annahmen zu umgehen, die Tabelle mit der Index-Anfrage müsste als Spalten enthalten:
1. Alle Spalten, die im Index mit `key="true"` gekennzeichnet sind (Wert `null` in der row)
2. Alle Felder, die mit `key-type="user"` gekennzeichnet sind oder `KeyText` heißen (Wert des Feldes in der row)

----

Außerdem wird eine Exception geworfen, wenn das KeyText Feld leer ist, diese sollte auf jeden Fall abgefangen werden (auch wenn keine Fehlermeldung erscheint):

```
Caused by: java.lang.NullPointerException: Cannot invoke "aero.minova.rcp.model.Value.getStringValue()" because the return value of "aero.minova.rcp.model.form.MField.getValue()" is null
	at aero.minova.rcp.rcp.handlers.LoadFromMatchcode.execute(LoadFromMatchcode.java:78)
...
```

2023-02-01 07:11 UTC, Bauer-David commented
> Funktioniert prinzipel, allerdings werden folgende Annahmen gemacht:
> 
> * Die Indexview hat die Spalten `KeyLong` und `KeyText`
> * Es gibt genau eine ID-Spalte, die `KeyLong` heißen muss
> 
> Für den Großteil unserer Masken sollte das kein Problem sein, es muss uns aber bewusst sein.
> 
> Es wäre möglich, die Annahmen zu umgehen, die Tabelle mit der Index-Anfrage müsste als Spalten enthalten:
> 
> 1. Alle Spalten, die im Index mit `key="true"` gekennzeichnet sind (Wert `null` in der row)
> 2. Alle Felder, die mit `key-type="user"` gekennzeichnet sind oder `KeyText` heißen (Wert des Feldes in der row)
> 
> Außerdem wird eine Exception geworfen, wenn das KeyText Feld leer ist, diese sollte auf jeden Fall abgefangen werden (auch wenn keine Fehlermeldung erscheint):
> 
> ```
> Caused by: java.lang.NullPointerException: Cannot invoke "aero.minova.rcp.model.Value.getStringValue()" because the return value of "aero.minova.rcp.model.form.MField.getValue()" is null
> 	at aero.minova.rcp.rcp.handlers.LoadFromMatchcode.execute(LoadFromMatchcode.java:78)
> ...
> ```

Ich stelle mir aber die Frage, ob die Funktionalität in Masken ohne KeyText überhaupt gegeben sein sollte, da sie ja explizit für den Matchcode definiert wurde.

2023-02-01 07:24 UTC, janiak-minova commented
>Ich stelle mir aber die Frage, ob die Funktionalität in Masken ohne KeyText überhaupt gegeben sein sollte, da sie ja explizit für den Matchcode definiert wurde. @janiak-minova

Kann ich verstehen. Dann MUSS aber die Prüfung auf `key-type="user"` am Anfang raus. Ansonsten kommt es zu einem Fehler, wenn in der Maske nach dem KeyText-Feld noch ein `key-type="user"`-Feld kommt. 

Die "KeyLong ist die einzige ID-Spalte"-Annahme würde ich trotzdem versuchen zu umgehen, ansonsten muss es so dokumentiert werden.

2023-02-01 07:38 UTC, wis36 commented
Was spricht dagegen "nur" `key-type="user"` zu prüfen, wie bisher (9-11)?
Was hat das mit dem Index zu tun, es soll doch der Detailbereich geladen werden?

2023-02-01 07:49 UTC, janiak-minova commented
David hat schon recht, die Definition laut Doku ist "Matchcode", nicht `key-type="user"`. 

Meiner Meinung nach muss der Index genutzt werden, um aus dem KeyText die primär-Keys herauszufinden. Diese werden dann in der Read-Prozedur genutzt, um das Detail zu laden. 
Wie würdest du denn die Primary-Keys ohne den Index ermitteln @wis36?

2023-02-01 07:58 UTC, wis36 commented
Bisher wurden an die Read-Prozeduren alle Parameter des Detail übergeben. Die Prozedur selbst entscheidet dann, ob über KeyLong oder den (ebenfalls eindeutigen) KeyText geladen wird.

2023-02-01 08:33 UTC, janiak-minova commented
Aha... Das ist mir neu, dass wir unsere Read-Prozeduren so schreiben müssen, dass sie auch über den KeyText als Eingabewert funktionieren. Haben wir dazu eine ordentliche Doku? Ich finde, es ist eine sehr große Annahme, dass die Read-Prozedur sich schon darum kümmern wird. Ich habe eben mal ein paar durchgeschaut, z.B. bei xpcorReadEntryBooking fehlt die Abfrage nach der LastAction. Bei xpcorReadEmployee ist gar Abfrage für KeyText gegeben (Beide dieser Prozeduren haben wir nur aus dem alten Stand übernommen).

Zumindest die Freetables-Prozeduren habe ich bisher auch nicht so geschrieben, bei diesen würde der Ansatz also auf keinen Fall funktionieren. @Bauer-David, weißt du etwas davon?

2023-02-01 08:39 UTC, janiak-minova commented
@Bauer-David, die LastAction-Abfrage müsstest du in deinem Code tatsächlich noch ergänzen. In der Indexview-Anfrage noch eine Spalte "LastAction", mit einem Filter-Value >0.

2023-02-01 09:01 UTC, Bauer-David commented
> Aha... Das ist mir neu, dass wir unsere Read-Prozeduren so schreiben müssen, dass sie auch über den KeyText als Eingabewert funktionieren. Haben wir dazu eine ordentliche Doku? Ich finde, es ist eine sehr große Annahme, dass die Read-Prozedur sich schon darum kümmern wird. Ich habe eben mal ein paar durchgeschaut, z.B. bei xpcorReadEntryBooking fehlt die Abfrage nach der LastAction. Bei xpcorReadEmployee ist gar Abfrage für KeyText gegeben (Beide dieser Prozeduren haben wir nur aus dem alten Stand übernommen).
> 
> Zumindest die Freetables-Prozeduren habe ich bisher auch nicht so geschrieben, bei diesen würde der Ansatz also auf keinen Fall funktionieren. @Bauer-David, weißt du etwas davon?

Nope. Mir ist beim Umzug von den verschiedenen Masken, aber auch eine starke Inkonsistenz zwischen den Projekten aufgefallen. Daher würde ich persönlich es bei unserem Ansatz belassen, so sind wir auf der sicheren Seite, da damit die meisten kompatibel sind.

2023-02-01 09:28 UTC, wis36 commented
Inkonsistenzen gibt es natürlich, bei manchen Masken ist es gar nicht vorgesehen, anders implementiert oder der jeweilige Mitarbeiter wusste ggf. nichts von dieser Möglichkeit. Manchmal muss LastAction beachtet werden, manchmal nicht, je nach Tabelle. Es gibt auch manchmal mehrere Kriterien außer KeyText und LastAction, um eine Eindeutigkeit zu erreichen.

2023-02-01 09:35 UTC, janiak-minova commented
> oder der jeweilige Mitarbeiter wusste ggf. nichts von dieser Möglichkeit

Das ist halt genau das Problem, wir sind jetzt seit über 2 Jahren dabei und hören zum ersten Mal davon. Mit der neuen Variante muss man davon nichts wissen, es funktioniert trotzdem. Eine Indexview mit primary-key-Spalten muss auf jeden Fall gegeben sein, genauso wie die Read-Prozedur die primary-Keys auf jeden Fall verarbeiten kann. Deshalb würde ich auch bei der neuen Variante bleiben, sie erscheint mir wesentlich weniger fehleranfällig.

2023-02-01 10:04 UTC, wis36 commented
Klingt gut. Was machst du allerdings, wenn dieser Datensatz im Index nicht vorhanden ist?

2023-02-01 10:06 UTC, janiak-minova commented
Wenn der Datensatz im Index nicht vorhanden ist, dann sollte er meiner Meinung nach auch nicht geladen werden können... Was ist denn der Anwendungsfall, dass man einen Datensatz über den Index nicht finden kann, aber wenn man zufällig den Matchcode weiß, dann darf man ihn laden?

2023-02-01 10:08 UTC, wis36 commented
Da kann man vielleicht auch mal mit @MokMinova reden.
Anwendungsfälle:
1. ich möchte nicht erst Suche/Index benutzen, sondern lade nur den einen Datensatz
2. der Datensatz ist schon gelöscht und wird deshalb im Index nicht gefunden. Dadurch habe ich die Möglichkeit, den gelöschten Datensatz wiederherzustellen (Speichern setzt LastAction = 2)

2023-02-01 10:12 UTC, Bauer-David commented
> Da kann man vielleicht auch mal mit @MokMinova reden. Anwendungsfälle:
> 
> 1. ich möchte nicht erst Suche/Index benutzen, sondern lade nur den einen Datensatz
> 2. der Datensatz ist schon gelöscht und wird deshalb im Index nicht gefunden. Dadurch habe ich die Möglichkeit, den gelöschten Datensatz wiederherzustellen (Speichern setzt LastAction = 2)

Diese Möglichkeit besteht in der aktuellen Anwendung nicht. Das würde für uns bedeuten, dass wir viel ändern müssten. Das Konzept des WFCs wurde mit SAW erstellt und die Funktion war nicht vorgesehen, daher würde ich jetzt nicht alles umschmeißen nur dafür, was wahrscheinlich die wenigsten Kunden nutzen.

2023-02-01 10:13 UTC, janiak-minova commented
1. Der Index muss nicht geladen sein. Es wird nur die gleiche View/Tabelle aufgerufen, das ist aber ein getrennter Aufruf, der direkt ans CAS geht.
2. Ich behaupte mal, dass so gut wie kein Kunde (und auch viele Kollegen) diesen Fall kennt und nutzen würde. Wir können die LastAction auch über die Datenbank ändern. Das halte ich für einen sehr kleinen Vorteil, dafür dass das Laden über F3 mit diesem Konzept eh in vielen Masken nicht funktionieren wird, weil die Prozeduren nicht "korrekt" geschrieben sind

2023-02-01 10:42 UTC, wis36 commented
Kathrin ist heute nicht da. Aber vielleicht hat sie dazu noch etwas. Falls was geändert wird, müsste man das wahrscheinlich sowieso mit Wilfried absprechen 😎

2023-02-06 11:18 UTC, MokMinova commented
Bin nicht sicher, ob meine Meinung noch gefragt ist. 

Grundsätzlich konnte mit F3 gesucht werden. Aber wie Stefan schon erwähnt hat ist es abhängig von der Maske, ob und wie der Datensatz gesucht wird. Bei Buchungsmasken kann nicht gelöscht werden, deswegen muss hier die LastAction = -1 nicht berücksichtigt werden.

Es ging bei der Funktion nur darum schneller Suchen zu können. Deswegen ist sie auch nur in einigen Masken implementiert gewesen. Es sollen keine gelöschten Datensätze wieder aktiviert werden können.

2023-02-06 14:22 UTC, CE7 approved these changes

2023-02-06 14:46 UTC, janiak-minova approved these changes

2023-02-06 14:47 UTC, merged