Bad #1440 staticvalues
minova-afis/aero.minova.rcp pull request #1442
Opened 2023-03-01 12:19 UTC by Bauer-David

closes #1440

2023-03-02 07:12 UTC, Bauer-David commented on tests/aero.minova.rcp.rcp.tests/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: JavaSE-11
Ist falsch, weiß nicht wie es sich eingeschlichen hat. Werde es korrigieren

2023-03-02 08:48 UTC, Bauer-David commented
Doku und Changelog erweitern!!!

2023-03-03 08:42 UTC, janiak-minova requested changes

2023-03-03 08:42 UTC, janiak-minova commented on bundles/aero.minova.rcp.model/src/aero/minova/rcp/model/form/ModelToViewModel.java
> +	public static MField convert(Field field, Locale locale, String timezone) {
Wofür braucht man hier die Zeitzone?

2023-03-03 08:42 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WFCDetailCASRequestsUtil.java
> +		setDefaultValues();
Hier muss die gleiche Reihenfolge gewählt werden, wie im WFCDetailPart. 
Am besten auch auch an beiden Stellen den Kommentar erweitern.

2023-03-03 08:42 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/util/WFCDetailCASRequestsUtil.java
> +					fieldAndOpName = field.getName().split(".");
Hier ist die Reihenfolge falsch. Der Feldname ist `<opName>.<fieldName>` 
-> fieldAndOpName[0] = opName, fieldAndOpName[1] = fieldName

im else Block ist es dann umgekehrt.

2023-03-03 10:15 UTC, janiak-minova approved these changes

2023-03-06 10:01 UTC, Bauer-David commented
Workflow Fehler wird mit #1445 gelöst

2023-03-06 10:30 UTC, janiak-minova requested changes

2023-03-06 10:30 UTC, janiak-minova commented on releng/pom.xml
> -    <version>12.7.4-SNAPSHOT</version>
Wieso wurde das entfernt?

2023-03-06 10:30 UTC, janiak-minova commented on .github/workflows/maven-ubuntu.yml
> +      - name: Set up Maven
Das ist jetzt ja auch schon im Main, hier löschen und Main mergen

2023-03-06 10:55 UTC, Bauer-David commented on releng/pom.xml
> -    <version>12.7.4-SNAPSHOT</version>
SonarLint Empfehlung

2023-03-06 11:49 UTC, merged