Pflichtfelder anpassen
minova-afis/aero.minova.rcp pull request #469
Opened 2021-04-27 13:06 UTC by janiak-minova

Pflichtfelder:
- Pflichtfelder werden farblich hervorgehoben, bis sie ausgefüllt sind
- Es kann nur gespeichert werden, wenn alle Pflichtfelder ausgefüllt sind

Textfelder:
- Maximallänge wird aus .xml ausgelesen
- Ist der Inhalt länger als die Maximallänge wird das Feld rot und es kann nicht gespeichert werden
- Bei Textfeldern über mehrere Zeilen erfolgt automatisch ein Zeilenumbruch am Ende des Feldes

Nummerfelder:
- Wenn in der .xml ein Maximal oder Minimal-Wert definiert ist wird geprüft, dass dieser eingehalten ist
- Bei über-/unterschreiten wird das Feld rot und es kann nicht gespeichert werden

closes #426 
closes #302

2021-05-03 06:35 UTC, CE7 requested changes
Soweit ist es verständlich. Bitte zu den Code-Blöcken die eingeführt wurden auch noch kommentare eintragen.

2021-05-03 06:35 UTC, CE7 commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/fields/BooleanField.java
>  		formData.top = new FormAttachment(composite, MARGIN_TOP + row * COLUMN_HEIGHT);
Kommentar bitte

2021-05-03 06:54 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/fields/BooleanField.java
>  		formData.top = new FormAttachment(composite, MARGIN_TOP + row * COLUMN_HEIGHT);
Siehe neuen Commit

2021-05-04 05:57 UTC, CE7 approved these changes

2021-05-04 05:58 UTC, merged