Anfragen und Antworten des CAS werden geloggt
minova-afis/aero.minova.rcp pull request #479
Opened 2021-04-29 10:38 UTC by janiak-minova

Logfile: < Workspace Ordner >/.metadata/.log

Beispielhaftes Logfile ist angehängt (Anlegen eines Spontantests).
[Logfile.txt](https://github.com/minova-afis/aero.minova.rcp/files/6397943/Logfile.txt)

closes #475

2021-05-03 06:42 UTC, CE7 requested changes

2021-05-03 06:42 UTC, CE7 commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/fields/LookupField.java
>  					t.fillSelectedValue();
Wenn wir es nicht mehr brauchen, dann direkt Löschen

2021-05-03 06:42 UTC, CE7 commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/handlers/TraverseListenerImpl.java
>  		List<MSection> pageList;
Entfernen wenn es nicht gebraucht wird

2021-05-03 06:42 UTC, CE7 commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/handlers/TraverseListenerImpl.java
>  			break;
Wenn wir die anderen Fälle nicht benötigen lieber entfernen anstatt nur auskommentieren

2021-05-03 11:44 UTC, janiak-minova commented on bundles/aero.minova.rcp.rcp/src/aero/minova/rcp/rcp/handlers/TraverseListenerImpl.java
>  			break;
Siehe neuen Commit

2021-05-04 09:10 UTC, CE7 approved these changes

2021-05-04 09:10 UTC, merged