#893 prefstooltip
minova-afis/aero.minova.rcp pull request #981
Opened 2021-11-05 07:52 UTC by Bauer-David

2021-11-05 07:53 UTC, Bauer-David commented
Sobald Pull-Request #979 durch ist, muss noch das Tooltip für die Comboboxen gesetzt werden.

2021-11-17 07:27 UTC, CE7 requested changes

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWChooser.java
> +			label.setToolTipText(getTooltip());
Warum tun wir das hier?

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWCombo.java
> +			combo.setToolTipText(getTooltip());
gleicher Fall, wieso machen wir das hier?

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWIntegerText.java
> +				text.setToolTipText(getTooltip());
Warum?

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWIntegerText.java
> +				text.setToolTipText(getTooltip());
Warum?

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWText.java
> +			text.setToolTipText(getTooltip());
why?

2021-11-17 07:27 UTC, CE7 commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/SendLogsButton.java
> +			label.setToolTipText(getTooltip());
Wenn wir den Code 20 Mal verwenden, dann mach bitte eine Methode dafür?!

2021-11-17 07:31 UTC, janiak-minova commented
Bitte auch Pullrequests in Invoice und Workingtime erstellen, und die Klassen InvoicePreferencePage und WorkingTimePreferencePage anpassen

2021-11-29 15:10 UTC, janiak-minova commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWWidget.java
> +		if (getTooltip() != null && getTooltip().isBlank())
Den Check kann man sich ganz sparen, es schadet nicht wenn der Tooltip null oder leer ist.

Außerdem wird der Tooltip gerade nur gesetzt, wenn er blank ist (höchstens Leerzeichen enthält). Ist das so gewünscht?

Wir wollen bei ifs immer Klammern haben, auch wenn es nur eine Zeile Code im Block ist

2021-11-29 15:10 UTC, janiak-minova commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/DateFormattingWidget.java
> +		// not needed
Warum dann nicht entfernen?

2021-11-30 07:25 UTC, Bauer-David commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/DateFormattingWidget.java
> +		// not needed
Ist wegen dem Extend eine Pflichtmethode. Wir prüfen aber den Wert nicht.

2021-11-30 07:34 UTC, Bauer-David commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWWidget.java
> +		if (getTooltip() != null && getTooltip().isBlank())
Ich lasse den Check auf null, da wir Tooltips nur dann setzen, wenn es sinnvoll ist. Wenn kein Tooltip gebraucht wird, setzen wir null.

2021-11-30 07:45 UTC, janiak-minova commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWWidget.java
> +		if (getTooltip() != null && getTooltip().isBlank())
Auf null oder gar nicht setzen läuft an der Stelle aber aufs gleiche raus. Man könnte sich die Methode sparen, weil es dann nur noch eine einzelne Zeile ist.

2021-11-30 10:46 UTC, Bauer-David commented on bundles/aero.minova.rcp.preferencewindow/src/aero/minova/rcp/preferencewindow/control/CustomPWWidget.java
> +		if (getTooltip() != null && getTooltip().isBlank())
Gar nicht setzen geht nicht, da es ein Parameter ist. Daher entweder null oder tatsächlicher Wert.

2021-12-01 13:15 UTC, CE7 approved these changes
Passt

2021-12-01 13:15 UTC, merged